### ISSUE TITLE
feedback on deploying aggregation service

### ISSUE THREAD

**Issue by k-o-ta** [privacysandbox/aggregation-service#11]
I got an api gateway error `The API with ID my-api-id doesn’t include a route with path /* having an integration arn:aws:lambda:us-east-1:my-aws-account-id:function:stg-create-job.`  on aws console, after deploying aggregation service using terraform.

I changed Source ARN of lambda's permisson from `arn:aws:execute-api:us-east-1:my-aws-account-id:my-api-id/*/**` to `arn:aws:execute-api:us-east-1:my-aws-account-id:my-api-id/*/*/v1alpha/getJob`, and it solved the error.
https://github.com/privacysandbox/control-plane-shared-libraries/blob/9efe5591acc18e46263399d9785432a146d9675c/operator/terraform/aws/modules/frontend/api_gateway.tf#L62

**Comment by hostirosti** [comment]
Hi @k-o-ta,

thank you for reporting this, we will look into it. Can you share which Terraform version you used?

**Comment by k-o-ta** [comment]
Thank you for reply.
My Terraform version was v1.2.3.
```
% terraform --version
Terraform v1.2.3
on darwin_amd64
```

I would like to correct some of the issue description.
Correct:  `arn:aws:execute-api:us-east-1:my-aws-account-id:my-api-id/*/*/v1alpha/createJob`
Inorrect: `arn:aws:execute-api:us-east-1:my-aws-account-id:my-api-id/*/*/v1alpha/getJob`

Additionally, the API call succeeds, although an error is displayed on the console screen.

**Comment by hostirosti** [comment]
Hi @k-o-ta ,

thank you, can you test if you're still able to reproduce the issue on your end using release `v0.5.0`?

Thank you in advance,
Robert

**Comment by k-o-ta** [comment]
I'm sorry for late reply.

I retried using `v0.8.0`, but it reproduced the same error.

<img width="1436" alt="include-a-route-with-path" src="https://user-images.githubusercontent.com/5237032/227471073-94fc2147-0d66-499e-bbcf-29f4840489a7.png">

**Comment by hostirosti** [comment]
Hi @k-o-ta ,

thank you for the details. I was able to reproduce that on our end and we'll look into addressing this issue. This should not be interfering with normal operations of the service as you stated as well. We recommend to not change the path for the time being till we have a version that is tested fully during our releases.

**Comment by hostirosti** [comment]
Hi @k-o-ta, this issue has been addressed with our latest release version `0.10.0` that uses version [0.51.13](https://github.com/privacysandbox/control-plane-shared-libraries/releases/tag/v0.51.13) of our shared libraries. 
Thank you for reporting this issue and for your patience.
