### ISSUE TITLE
Unable to copy AMI image to my AWS account

### ISSUE THREAD

**Issue by grzechukol** [privacysandbox/aggregation-service#12]
The documentation states that:
> Note: The prebuilt Amazon Machine Image (AMI) for the aggregation service is only available in the us-east-1 region. If you like to deploy the aggregation service in a different region you need to copy the released AMI to your account or build it using our provided scripts.

Ref. https://github.com/privacysandbox/aggregation-service#download-terraform-scripts-and-prebuilt-dependencies

When I try to copy the AMI to my account I'm getting the following error:
```
Failed to copy ami-036942f537f7a7c2b
You do not have permission to access the storage of this ami
```
Can you give me some guidance or tell me if it's a configuration error?

Context:

<img width="817" alt="image" src="https://user-images.githubusercontent.com/4355958/215733743-c27724c2-6381-4ffa-a2e3-7a7c3b1fb362.png">

**Comment by hostirosti** [comment]
Hi @grzechukol,

thank you for reporting this issue. We have adjusted the permission for the underlying image snapshot. The AMI copy should now be possible.

Please let us know if you still can't copy the AMI.

Cheers,
Robert

**Comment by grzechukol** [comment]
I can confirm that it works as expected.

Context:

When I run the copy with the following settings:
<img width="820" alt="image" src="https://user-images.githubusercontent.com/4355958/219012193-d1e7f639-b4d5-411e-8ece-2ec5049bf390.png">
I'm getting the following output:
```
AMI copy operation for ami-036942f537f7a7c2b initiated
It can take a few minutes for the AMI to be copied. You can check the progress of the operation in the AMI table in us-west-1. The AMI ID of the new AMI is ami-REDACTED.
```
