### ISSUE TITLE
aggregation-service-artifacts-build CodeBuild built the AMI at the wrong region

### ISSUE THREAD

**Issue by khalilj-appsflyer** [privacysandbox/aggregation-service#17]
Running the step "Building artifacts" from https://github.com/privacysandbox/aggregation-service/blob/main/build-scripts/aws/README.md#building-artifacts
To build the artifacts on region: eu-west-1

The CodeBuild failedwith the below error:
> 836 | --> amazon-ebs.sample-ami: AMIs were created:
> 837 | us-east-1: ami-069b14bccedc04571
> ....
> [Container] 2023/05/09 15:34:31 Running command bash build-scripts/aws/set_ami_to_public.sh set_ami_to_public_by_prefix aggregation-service-enclave_$(cat VERSION) $AWS_DEFAULT_REGION $AWS_ACCOUNT_ID
> 841 |  
> 842 | An error occurred (InvalidAMIID.Malformed) when calling the ModifyImageAttribute operation: Invalid id: "" (expecting "ami-...")
> 843 |  
> 844 | An error occurred (MissingParameter) when calling the ModifySnapshotAttribute operation: Value () for parameter snapshotId is invalid. Parameter may not be null or empty.
> 845

The reason is that it created the ami on us-east-1 instead of eu-west-1

**Comment by hostirosti** [comment]
Hi @khalilj-appsflyer,
thank you for reporting this issue. We currently support us-east-1 as our main build region and will look into supporting other regions soon. Can you verify you're successful building in us-east-1?

**Comment by maybellineboon** [comment]
Hi @khalilj-appsflyer ,

Let us know if you still need assistance.
