### ISSUE TITLE
aggregation-service-artifacts-build CodeBuild build AMI fails on yum lock

### ISSUE THREAD

**Issue by khalilj-appsflyer** [privacysandbox/aggregation-service#18]
Running the step "Building artifacts" from https://github.com/privacysandbox/aggregation-service/blob/main/build-scripts/aws/README.md#building-artifacts
To build the artifacts on region: eu-west-1

The CodeBuild failed with the below error:

> amazon-ebs.sample-ami: Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
> --
> 754 | ==> amazon-ebs.sample-ami: Existing lock /var/run/yum.pid: another copy is running as pid 3465.
> 755 | ==> amazon-ebs.sample-ami: Another app is currently holding the yum lock; waiting for it to exit...
> 
>

**Comment by hostirosti** [comment]
Hi @khalilj-appsflyer,
thank you for reporting this issue. We currently support us-east-1 as our main build region and will look into supporting other regions soon. Can you verify you're successful building in us-east-1?

**Comment by maybellineboon** [comment]
hi @khalilj-appsflyer ,

Since we have not received a response for some time, we'll proceed to close this.

Let us know if you still need some assistance.
