### ISSUE TITLE
Aggregation service deployment using user provided vpc fails

### ISSUE THREAD

**Issue by khalilj-appsflyer** [privacysandbox/aggregation-service#20]
When specifying "enable_user_provided_vpc = true", creation of the environment following the instructions at https://github.com/privacysandbox/aggregation-service/tree/main#set-up-your-deployment-environment
fails with error:
Out of index vpc[0],  182:   dynamodb_vpc_endpoint_id = module.vpc[0].dynamodb_vpc_endpoint_id

At file: terraform/aws/applications/operator-service/main.tf
Lines 182 & 183 refers to module.vpc[0]
While module.vpc is not set when "enable_user_provided_vpc = true"
module "vpc" {
  count  = var.enable_user_provided_vpc ? 0 : 1

**Comment by hostirosti** [comment]
Hi @khalilj-appsflyer,
thank you for reporting this issue. We'll look into resolution.

**Comment by hostirosti** [comment]
Hi @khalilj-appsflyer,

can you verify if you've set the other required variables when setting `enable_user_provided_vpc = true`?
`user_provided_vpc_subnet_ids` and `user_provided_vpc_security_group_ids` need to be set in your <env>.auto.tfvars as well.

[excerpt from operator/terraform/aws/environments/shared/operator_service_variables.tf](https://github.com/privacysandbox/control-plane-shared-libraries/blob/v0.51.15/operator/terraform/aws/environments/shared/operator_service_variables.tf#LL401)
```
...
################################################################################
# VPC, subnets and security group variables
################################################################################

variable "enable_user_provided_vpc" {
  description = "Allow providing existing vpc details as input."
  type        = bool
  default     = false
}

variable "user_provided_vpc_subnet_ids" {
  description = "Customized VPC subnet ids for worker autoscaling group"
  type        = list(string)
  default     = []
}

variable "user_provided_vpc_security_group_ids" {
  description = "Customized VPC security group ids for worker autoscaling group"
  type        = list(string)
  default     = []
}
...
```

**Comment by maybellineboon** [comment]
Hi @khalilj-appsflyer ,

Since we have not received a response for some time, we'll proceed to close out this issue.

Let us know if you still need assistance.
