### ISSUE TITLE
Missing required properties: jobKey

### ISSUE THREAD

**Issue by olegkushniriov** [privacysandbox/aggregation-service#21]
Hello,

While executing /createJob request with following payload 
Please see an example below:
`
{
    "job_request_id": "Job-1010",
    "input_data_blob_prefix": "reports/inputs/input.avro",
    "input_data_bucket_name": "test-android-sandbox",
    "output_data_blob_prefix": "reports/output/result_1.avro",
    "output_data_bucket_name": "test-android-sandbox",
    "job_parameters": {
        "output_domain_blob_prefix": "reports/domains/domain.avro",
        "output_domain_bucket_name": "test-android-sandbox",
        "debug_privacy_epsilon": 30
    }
}
`
The response of this request will be 202

When executing /getJob?job_request_id=Job-1010

`
{
    "job_status": "IN_PROGRESS",
    "request_received_at": "2023-06-12T15:14:17.891601Z",
    "request_updated_at": "2023-06-12T15:14:23.222830Z",
    "job_request_id": "Job-1010",
    "input_data_blob_prefix": "reports/inputs/input.avro",
    "input_data_bucket_name": "test-android-sandbox",
    "output_data_blob_prefix": "reports/output/result_1.avro",
    "output_data_bucket_name": "test-android-sandbox",
    "postback_url": "",
    "result_info": {
        "return_code": "",
        "return_message": "",
        "error_summary": {
            "error_counts": [],
            "error_messages": [
                "Missing required properties: jobKey"
            ]
        },
        "finished_at": "1970-01-01T00:00:00Z"
    },
    "job_parameters": {
        "debug_privacy_epsilon": "30",
        "output_domain_bucket_name": "test-android-sandbox",
        "output_domain_blob_prefix": "reports/domains/domain.avro"
    },
    "request_processing_started_at": "2023-06-12T15:14:23.133071Z"
}`

The error is Missing required properties: jobKey
The job stays in status IN_PROGRESS

When running same /createJob request without the job_request_id property - 
the response from /createJob will be:

`
{
    "code": 3,
    "message": "Missing required properties: jobRequestId\r\n in: {\n    \"input_data_blob_prefix\": \"reports/inputs/input.avro\",\n    \"input_data_bucket_name\": \"test-android-sandbox\",\n    \"output_data_blob_prefix\": \"reports/output/result_1.avro\",\n    \"output_data_bucket_name\": \"test-android-sandbox\",\n    \"job_parameters\": {\n        \"output_domain_blob_prefix\": \"reports/domains/domain.avro\",\n        \"output_domain_bucket_name\": \"test-android-sandbox\"\n    }\n}",
    "details": [
        {
            "reason": "JSON_ERROR",
            "domain": "",
            "metadata": {}
        }
    ]
}`

**Comment by hostirosti** [comment]
Hi @olegkushniriov,

thank you for reporting this issue. We are looking into resolution. This appears to happen when the `"attribution_report_to": "<your_attribution_domain>",` is missing from `"job_parameters"` in the createJob API call. 
We'll add additional validation of the createJob API and mark `"attribution_report_to"` as a required parameter.

**Comment by ruclohani** [comment]
FYI - This issue is fixed in the latest release 0.10.0.
