### ISSUE TITLE
Decode the final `output.json` from the `LocalTestingTool`

### ISSUE THREAD

**Issue by ydennisy** [privacysandbox/aggregation-service#22]
Hi,

I have managed to get the full flow running to aggregate debug reports in the browser and process them locally with the provided tool.

The final file output I have is:

```json
[{"bucket": "d0ZHnRzgTJMAAAAAAAAAAA==", "metric": 195000}]
```

Which looks correct in terms of there should be a single key and the metric value is correct.

The issue I have is now decoding this `bucket` to get my original input data, I assumed the steps would be:
- base64 decode
- CBOR decode

But this causes the following error:

```
_cbor2.CBORDecodeEOF: premature end of stream (expected to read 23 bytes, got 15 instead)
```

Would really appreciate any help on how to get the input data back out of this bucket.

Best,
D

**Comment by maybellineboon** [comment]
Hi Dennis,

Please do a base64 decode on the bucket and you should be able to get your key.

Thanks!
