### ISSUE TITLE
Unable to test noise addition using the local aggregation service tool 

### ISSUE THREAD

**Issue by sanjalijha** [privacysandbox/aggregation-service#24]
Hi, I work in the Google Ad Traffic Quality Team. I am using the local aggregation service tool to simulate noise on locally generated aggregatable reports. However, due to the contribution budget limits, I am unable to create multiple aggregatable reports that will correctly represent my data. What is the best way for me to test this locally, can I manually create an aggregatable report with very high values (corresponding to a raw summary report) for testing?

**Comment by maybellineboon** [comment]
Hi,

For [Attribution Reporting API](https://github.com/WICG/attribution-reporting-api/blob/main/AGGREGATE.md), you can go to chrome://attribution-internals and be able to "Clear all attribution data". This will allow for you to test and create new source and trigger registration.

**Comment by maybellineboon** [comment]
Hi @sanjalijha ,

Closing this. Let us know if you still require some help.
