### ISSUE TITLE
How to copy AMI to another region?

### ISSUE THREAD

**Issue by JonathanAquino-NextRoll** [privacysandbox/aggregation-service#32]
In the [AWS instructions](https://github.com/privacysandbox/aggregation-service/blob/b5c9c0015220b4631e6a8ca1df9ea36e20c32dee/docs/aws-aggregation-service.md), there are two options for using the AMI in a region other than us-east-1:

> If you like to deploy the aggregation service in a different region you need to copy the released AMI to your account or build it using our provided scripts.

I have been having a [lot of trouble](https://github.com/privacysandbox/aggregation-service/issues/31) building the AMI using the provided scripts, so I would like to try simply copying the AMI (the first option), but I don't see instructions for this. What is the AMI name and where do I get it from? Do I need to change any parameters to point to the new region? What step should I move on to after copying the AMI?

Could you add instructions for copying the AMI and subsequent steps?

**Comment by maybellineboon** [comment]
Hi @JonathanAquino-NextRoll ,

We'll publish this as part of the [AWS instructions](https://github.com/privacysandbox/aggregation-service/blob/main/docs/aws-aggregation-service.md).

**Comment by maybellineboon** [comment]
Closing this as we have published instructions for copying the AMI to another region.
