### ISSUE TITLE
Could you provide encrypted sample report for testing?

### ISSUE THREAD

**Issue by JonathanAquino-NextRoll** [privacysandbox/aggregation-service#33]
I have the aggregation service set up, but our system to produce encrypted reports is not ready to go yet. This repo's [sampledata](https://github.com/privacysandbox/aggregation-service/tree/main/sampledata) directory has a sample report, but it is unencrypted and so only works with the local testing tool only, not with AWS Nitro Enclaves.

Could you provide, either in the repo or in a zip file in this thread, an encrypted sample output.avro and accompanying domain.avrp that we can use to test our AWS aggregation service to make sure everything is running properly?

**Comment by maybellineboon** [comment]
Hi @JonathanAquino-NextRoll ,

Unfortunately, we can't provide sampledata for avro reports. However, we are planning to publish some guidance on creating these reports. We have shared this with NextRoll and will publish once available.

Thanks!
