### ISSUE TITLE
Aggregation Service: Run a job without output domain. Unable to set domain_optional flag

### ISSUE THREAD

**Issue by pisutpon** [privacysandbox/aggregation-service#38]
I am trying to process a job without an output domain. I found the domain_optional flag in the AggregationWorkerArgs class ([link](https://github.com/privacysandbox/aggregation-service/blob/main/java/com/google/aggregate/adtech/worker/AggregationWorkerArgs.java#L346)). I can’t set this flag as a JobParameter. Can you guide me on how to set the flag?

**Comment by maybellineboon** [comment]
Hi @pisutpon ,

Thanks for reaching out. This [option](https://github.com/privacysandbox/aggregation-service/blob/main/java/com/google/aggregate/adtech/worker/AggregationWorkerArgs.java#L346) is not a JobParameter but a runtime flag used for LocalTestingTool where you can use the `--skip_domain` parameter.

Optional domain is currently not available for Aggregation Service on Trusted Execution Environment.

**Comment by maybellineboon** [comment]
Closing since response has been provided.
