### ISSUE TITLE
Confused about the output_domain.avro

### ISSUE THREAD

**Issue by yanghuang1028** [privacysandbox/aggregation-service#46]
Hi aggregation-service team,

I'm really confused about the file "output_domain.avro" used for producing a summary report locally. In your nodejs example([code](https://github.com/GoogleChromeLabs/trust-safety-demo/blob/8f3d874b79ab0c8a15822fbcd09e94042aee7dcd/conversion-measurement/functions/apps/adtech.js#L170)), how can I generate a "output_domain.avro" for the aggregation report ? 

Here is your sample doc: https://github.com/privacysandbox/aggregation-service/blob/main/docs/collecting.md#collecting-and-batching-aggregatable-reports 

```
{
    "bucket": "\u0005Y"
}
```

Will this "output_domain.avro" work for your nodejs example ?

If convenient, could you explain what this domain file is generated according to ? Thanks a lot !!

**Comment by maybellineboon** [comment]
Hi @yanghuang1028 ,

The example [code](https://github.com/GoogleChromeLabs/trust-safety-demo/blob/8f3d874b79ab0c8a15822fbcd09e94042aee7dcd/conversion-measurement/functions/apps/adtech.js#L170) is not our sample code for privacy sandbox. The output_domain.avro file is a file that will contain the domain keys that you wish to retrieve from the aggregatable reports generated by the measurements APIs like Attribution Reporting API and Private Aggregation API. Currently, you would be required to [pre-declare](https://github.com/WICG/attribution-reporting-api/blob/main/AGGREGATION_SERVICE_TEE.md#pre-declaring-aggregation-buckets) the keys that you want to get from the aggregatable reports. When you batch in Aggregation Service, you will need to include the location of your output_domain files.

The output domain is created using the an [avro schema](https://github.com/privacysandbox/aggregation-service/blob/main/docs/collecting.md#output_domainavsc) of a key-value pair. The key being the "bucket" and the value being the domain key.

```
{
    "bucket": "\u0005Y"
}
```

The domain key format is a 128-bit integer encoded as a 16-byte big-endian bytestring.

Domain keys are 128-bit keys designed by you which will contain different dimensions that you would wish to collect/aggregate. This [section](https://developers.google.com/privacy-sandbox/relevance/attribution-reporting/aggregation-keys) of the Attribution Reporting API handbook should help explain more about keys.

**Comment by yanghuang1028** [comment]
Thanks a lot ! really help me !!
