### ISSUE TITLE
403 errors when deploying aggregation-service

### ISSUE THREAD

**Issue by yanghuang1028** [privacysandbox/aggregation-service#47]
Hi team,
 
I’m trying to set up our deployment environment. But I encountered this error. Could you please help to look at it ? Thanks a lot !!!
 
These are the roles of our service accounts. Do I need to add some additional role permissions?
our projectId: ecs-1709881683838
<img width="1559" alt="image001" src="https://github.com/privacysandbox/aggregation-service/assets/48471702/7f2038ab-45cf-4f96-95f5-79066b2b3e54">

```
Error: Error creating function: googleapi: Error 403: Could not create Cloud Run service dev-us-west2-worker-scale-in. Permission ‘iam.serviceaccounts.actAs’ denied on service account [worker-sa-aggregation-service@microsites-sa.iam.gserviceaccount.com](mailto:worker-sa-aggregation-service@microsites-sa.iam.gserviceaccount.com) (or it may not exist).
│
│   with module.job_service.module.autoscaling.google_cloudfunctions2_function.worker_scale_in_cloudfunction,
│   on ../../coordinator-services-and-shared-libraries/operator/terraform/gcp/modules/autoscaling/workerscalein.tf line 35, in resource “google_cloudfunctions2_function” “worker_scale_in_cloudfunction”:
│   35: resource “google_cloudfunctions2_function” “worker_scale_in_cloudfunction” {
│
╵
╷
│ Error: Error creating function: googleapi: Error 403: Could not create Cloud Run service dev-us-west2-frontend-service. Permission ‘iam.serviceaccounts.actAs’ denied on service account [dev-frontend@microsites-sa.iam.gserviceaccount.com](mailto:dev-frontend@microsites-sa.iam.gserviceaccount.com) (or it may not exist).
│
│   with module.job_service.module.frontend.google_cloudfunctions2_function.frontend_service_cloudfunction,
│   on ../../coordinator-services-and-shared-libraries/operator/terraform/gcp/modules/frontend/main.tf line 43, in resource “google_cloudfunctions2_function” “frontend_service_cloudfunction”:
│   43: resource “google_cloudfunctions2_function” “frontend_service_cloudfunction” {
│
╵
╷
│ Error: Error creating instance template: googleapi: Error 409: The resource ‘projects/ecs-1709881683838/global/instanceTemplates/dev-collector’ already exists, alreadyExists
│
│   with module.job_service.module.worker.google_compute_instance_template.collector,
│   on ../../coordinator-services-and-shared-libraries/operator/terraform/gcp/modules/worker/collector.tf line 49, in resource “google_compute_instance_template” “collector”:
│   49: resource “google_compute_instance_template” “collector” {
```

**Comment by maybellineboon** [comment]
Hi @yanghuang1028 ,

Thanks for reaching out. Just to check, did you use the [terraform script](https://github.com/privacysandbox/aggregation-service/blob/main/docs/gcp-aggregation-service.md#adtech-setup-terraform) when deploying your aggregation service deploy and worker?

You will need to run this when creating/updating your worker so that they are provided with the appropriate access. You can update the section below in the `<repository>/terraform/gcp/environments/adtech_setup` folder.

```
# [1] Uncomment below lines if you like Terraform grant needed permissions to
# pre-existing service accounts
# deploy_service_account_email = "<YourDeployServiceAccountName>@<ProjectID>.iam.gserviceaccount.com"
# worker_service_account_email = "<YourWorkerServiceAccountName>@<ProjectID>.iam.gserviceaccount.com"
```

**Comment by yanghuang1028** [comment]
Hi @maybellineboon ,

I used the service account "sa-aggregation-service@microsites-sa.iam.gserviceaccount.com" to run the terraform script, and actually the service accounts I used all have the **ServiceAccountUser** permission. However, it still threw the **Permission 'iam.serviceaccounts.actAs'** error, which is a bit wired...
![image](https://github.com/privacysandbox/aggregation-service/assets/48471702/d414e649-addc-44b5-9519-02767f9dbc61)
<img width="1579" alt="image" src="https://github.com/privacysandbox/aggregation-service/assets/48471702/e6387fb8-c8b5-4e5a-8457-a6dca42f8aac">

**Comment by hostirosti** [comment]
Hi @yanghuang1028,

can you try to grant that permission for `sa-aggregation-service@microsites-sa.iam.gserviceaccount.com` directly on the 2 service accounts (`worker-sa-aggregation-service@microsites-sa.iam.gserviceaccount.com` and `dev-frontend@microsites-sa.iam.gserviceaccount.com`). You find the permission tab on the service account details page itself 
<img width="518" alt="image" src="https://github.com/privacysandbox/aggregation-service/assets/1919833/9fd739e4-b554-4968-bf55-175663bfacac">
Where you can grant access to specific principals:
<img width="369" alt="image" src="https://github.com/privacysandbox/aggregation-service/assets/1919833/799e9133-b348-4107-ba4e-7ea5aa2361e0">

**Comment by hostirosti** [comment]
Hi @yanghuang1028, you can ask for a consultation meeting through your partner manager contact on Google side. They'll schedule one.

To my knowledge, the service accounts you use as part of the deployment need to be created in the project you deploy the aggregation service to. I did some non-extensive testing in this area in the past and was unsuccessful to use a service account created in a different project in all parts of the aggregation service (notably the worker service account). 

It looks like the way your company likes to organize / manage service accounts is not supported by GCP to run aggregation service.

**Comment by yanghuang1028** [comment]
Hi @hostirosti,

okay, thanks a lot !!

I'll contact with our partner manager to discuss about this. really thanks!!
