### ISSUE TITLE
Aggregation job failing in AWS with error DECRYPTION_KEY_NOT_FOUND

### ISSUE THREAD

**Issue by NikitaBedmutha** [privacysandbox/aggregation-service#56]
I am able to trigger the aggregation job with /createJob endpoint deployed via terraform in aws. While running the /getJob with the request id, I am getting below error:

`"result_info": {
        "return_code": "REPORTS_WITH_ERRORS_EXCEEDED_THRESHOLD",
        "return_message": "Aggregation job failed early because the number of reports excluded from aggregation exceeded threshold.",
        "error_summary": {
            "error_counts": [
                {
                    "category": "DECRYPTION_KEY_NOT_FOUND",
                    "count": 1,
                    "description": "Could not find decryption key on private key endpoint."
                },
                {
                    "category": "NUM_REPORTS_WITH_ERRORS",
                    "count": 1,
                    "description": "Total number of reports that had an error. These reports were not considered in aggregation. See additional error messages for details on specific reasons."
                }
            ],
            "error_messages": []
        },
        "finished_at": "2024-05-0`

I could see @ydennisy also had similar issue but could not find the solution for it.

**Comment by chasinandrew** [comment]
Hello @NikitaBedmutha! This error could be caused by an issue with the trigger registration. Can you confirm that this is set correctly? Documentation for how this is set can be found [here](https://github.com/WICG/attribution-reporting-api/blob/main/AGGREGATE.md#data-processing-through-a-secure-aggregation-service).

**Comment by NikitaBedmutha** [comment]
Thanks @chasinandrew , it was a valid one, but I retried and it worked. However I am facing PRIVACY_BUDGET_AUTHORIZATION_ERROR‬ now. I suspect its because the reporting origin is different than AWS ID’s onboarded reporting site(where we had just registered our top level domain and not our actual reporting origin site). How do we fix this now? Any leads would be helpful. Thanks in advance.

**Comment by chasinandrew** [comment]
@NikitaBedmutha What is your reporting site?

**Comment by hostirosti** [comment]
@NikitaBedmutha please communicate ad tech specific information (onboarding data like service accounts and sites) through our support email.
