### ISSUE TITLE
Aggregation service job showed "Service Error"

### ISSUE THREAD

**Issue by evazkj** [privacysandbox/aggregation-service#63]
Hi, I was testing the Aggregation Service deployed in AWS (version 2.5.0). I met an error shows:
```
"result_info": {
        "return_code": "REPORTS_WITH_ERRORS_EXCEEDED_THRESHOLD",
        "return_message": "Aggregation job failed early because the number of reports excluded from aggregation exceeded threshold.",
        "error_summary": {
            "error_counts": [
                {
                    "category": "SERVICE_ERROR",
                    "count": 1,
                    "description": "Internal error occurred during operation."
                },
                {
                    "category": "NUM_REPORTS_WITH_ERRORS",
                    "count": 1,
                    "description": "Total number of reports that had an error. These reports were not considered in aggregation. See additional error messages for details on specific reasons."
                }
            ],
            "error_messages": []
        },
        "finished_at": "2024-07-01T22:02:32.089351102Z"
    },
```
I was testing only 1 reports in the batch, tried local-testing with the cleartext version, which works fine. 

Without the additional information, I wasn't able to identify the problem. 

By any chance I am not the only one who met this problem? What else should I check? Thanks

**Comment by nlrussell** [comment]
Hi @evazkj, can you retry the job and update here if you're still facing the error? SERVICE_ERROR can be an intermittent internal error within the Aggregation Service service during operation.

**Comment by evazkj** [comment]
Still facing this error. I even tried destroy and redeploy the instance.

**Comment by evazkj** [comment]
I sent an email containing the details to [aggregation-service-support@google.com](mailto:aggregation-service-support@google.com). Thanks!

**Comment by evazkj** [comment]
The problem has been resolved. The problem is we used un-updated coordinator id. Fixed it by destroy/reboot. Thanks!
