### ISSUE TITLE
Help: Aggregation-service returning metric incompatible with the number of conversions even with the scaled value

### ISSUE THREAD

**Issue by dbrito** [privacysandbox/aggregation-service#65]
Hello everyone, everything good ?

Guys, our team today has all the necessary attribution-reporting functionalities (source, trigger, sending of aggregated reports), and to test the functioning of attribution-reporting we served a creative through Admanager, this placement generated the expected conversions (the page conversion is the same destination page as the creative), but when generating the summary report it returns a metric that is completely different from the number of reports we have in our AWS bucket (each file is equivalent to a report record)

Does anyone have any idea how we could investigate the cause of this problem and eventually find a solution?

Example of a conversion or aggregatable report (**the value is scaled to mitigate noise 65534 is actually equivalent to 1**, in this case one conversion):

```js
//Histogram
[
 {
  "key": "0x9c3c00203e14ab93",
  "value": 65534
 }
]
```

```js
//Body
{
   "aggregation_coordinator_origin": "https://publickeyservice.msmt.aws.privacysandboxservices.com",
   "aggregation_service_payloads": [ {
      "key_id": "1f5e5273-b0db-40d9-942f-2142a9669330",
      "payload": "z3Fvi+NpvFRTK2ecgwP2fDJZgrqilmxRbQbeawZ50mp/HVJlD5fJAmXgmx0HWSaXXNCzV0iLswzrvKwHLqTrKq8hHucraB5d74Be99EAIfcx470LMTWtCa9tg0C7V3j5EXhLH4DjqscrEtpOr1K7qWLKoXr73iKxBF+MWTr+qHKLdcRvv7vU76cKWX19cMFjgKo0X0dHv5qJWPySZGcb4Y04wV9kLr0ucJZq8h1TI7j2wd5DsEytO/hdkm7/ipZX8N/ovRXRn/Mwqvj8cRRqhIRiWScoexL/mBdI18E87ZbO0aePPx3BTSv9m4+tGRKQGLGSFGdID7QoUniwv4SPZZUzrsfojEYZSa8+LnujBXa5Dp4Q37I4xegasjZirm8wH13uzYQ8al39JTMVnETSbo9JCdKZwbLKU6ViBD1DiTsqvFHhDZiK03wYvXMEJVmUbhgl+uDUF0C6bqV9zc/sBTzz/m7MW6N2penQKWeBnPVRq3l3Aqvr5G3SUC+XXehyhZj5A1j72F8UMQHv9vnvdo9v449REKZ133IJcqAfeene8xxLZ7+6F6/QNUYbXDbID4DCxU4QvbudFn5KI/I9MsFpIrCzyif8PiUq6MD4FFVszIsCo6wlkM6f4VZWxaA4jwSZygZqROOPwyEk3PqHxkcVU+Cz2KG64mrUi6GSVMH5Wwn7fUckviWUMhkADluFPYijXxJmTuq5KDJhnJ4cdoDZ9+4Q0U5hRT3Y6/VbQiqOXhiFV3d9mTBNnpHK2iI7iEZ5Ud2Zveyai+FAv5HI8ldY+UP4UJdaie6LLIwmThNaFYFUmhCb5tIrusROxYiDnZ1ss7Kn0wZBq0pK6Hb+F0wICOwQ2G4hJNuW0dv/2hHIWVv+dmNb0S6ciDQPDmNSk7EY+ViyQ8qeCruB9L6Rftd6p+unxBLHB4VXDji8vyh4SdpMgH6Wbf2/bsE60xeTb3sj06/r2qDjaeeDvv61oS3l3G7sAU8tNuK3eDjbknt7Sg8WZNIWKqs/VI/d0Lql8KB+ZaG9Vcw4cUIe+OY49BJpORY0zrSuJ5IW"
   } ],
   "shared_info": "{\"api\":\"attribution-reporting\",\"attribution_destination\":\"https://uol.com.br\",\"report_id\":\"055ffbe8-7c43-425a-af6f-ecd3938bd6a5\",\"reporting_origin\":\"https://attribution.ads.uol.com.br\",\"scheduled_report_time\":\"1720819104\",\"source_registration_time\":\"0\",\"version\":\"0.1\"}",
   "source_debug_key": "647775351539539"
}
```

CreateJob  request body:
*Batch of reports are processed per day
```js
{
    "input_data_blob_prefix": "report_2024_07_11",
    "input_data_bucket_name": "uolcsm-uolads-aggregate-reports",
    "output_data_blob_prefix": "output/summary_report.avro",
    "output_data_bucket_name": "uolcsm-uolads-aggregate-reports",
    "job_parameters": {           
        "attribution_report_to": "https://attribution.ads.uol.com.br",
        "output_domain_blob_prefix": "output_domain.avro",
        "output_domain_bucket_name": "uolcsm-uolads-aggregate-reports"
    },
    "job_request_id": "meuk20240710"
}
```

Print with the files from the AWS bucket (each file corresponds to a aggregatable report), the files are created from the path /.well-known/attribution-reporting/report-aggregate-attribution :
![image](https://github.com/user-attachments/assets/0c14188b-382e-4c06-8951-ec321970620d)

Metrics from summary report file:
*The expected metric should be something close to 2621360 (65534 * 40)
![image](https://github.com/user-attachments/assets/5995525a-648a-4295-96ff-e1bde273d7d1)

If anyone else has experienced this problem, I would greatly appreciate the help, because we have already tried on multiple days but the metric returned is always far from what was expected.

Thanks !

**Comment by nlrussell** [comment]
Hi @dbrito, can you provide the getJob response as well?

**Comment by maybellineboon** [comment]
hi @dbrito ,

Can you email Aggregation Service Support <aggregation-service-support@google.com> with your getJob response?

Pre-3PC deprecation, to better debug your issue, we suggest [enabling debugging for Attribution Reporting API](https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#optional-transitional-debugging-reports). You will receive debug enabled reports in the `.well-known/attribution-reporting/debug/report-event-attribution` endpoint with reports marked as "debug_enabled" in the shared_info field.

This will allow you to run Aggregation Service on debug mode by adding `"debug_run": "true"` in the job_parameters map. Once you run the job in debug_run, this will create 2 reports. One debug enabled and one summary report. The debug enabled report will provide you the noise that is added in the summary report.

Thanks!

**Comment by dbrito** [comment]
Hi @maybellineboon, I will implement this debug and generate these new reports, with this evidence I will also send the email to support

**Comment by dbrito** [comment]
@maybellineboon just one question, after activating debug (and looking here it seems that it was already activated), do I have to change anything in the way I create the .avro files for the aggregated report ? 

*Currently the file consists of the payload, key_id and shared_info fields
```js
const REPORTS_AVRO_SCHEMA = {
    "name": "AvroAggregatableReport",
    "type": "record",
    "fields": [
        { "name": "payload", "type": "bytes" },
        { "name": "key_id", "type": "string" },
        { "name": "shared_info", "type": "string" }
    ]
};
```

**Comment by maybellineboon** [comment]
Hi @dbrito ,

The current avro schema is still the same. No changes in the aggregatable report. The only difference you'll observe will be having the `debug_cleartext_payload` in the `aggregation_service_payloads` field and having the `\"debug_mode\":\"enabled\"` as part of the `shared_info` field.

Your createJob JSON body should look like this. And you should be able to generate the summary report and a debug summary report under your S3 bucket folder `output/debug/`
```
{
  "job_request_id": "<job_request_id>",
  "input_data_blob_prefix": "<report_folder>/<report_name>.avro",
  "input_data_bucket_name": "<input_bucket_name>",
  "output_data_blob_prefix": "<output_folder>/<summary_report_prefix>",
  "output_data_bucket_name": "<output_bucket_name>",
  "job_parameters": {
    "output_domain_blob_prefix": "<output_domain_folder>/<output_domain>.avro",
    "output_domain_bucket_name": "<output_domain_bucket_name>",
    "attribution_report_to": "<reporting origin of report>"
    "debug_run": "true"
  }
}
```

__Sample Debug Enabled Report:__

```
{
  "aggregation_coordinator_origin": "https://publickeyservice.msmt.aws.privacysandboxservices.com",
  "aggregation_service_payloads": [
    {
      "debug_cleartext_payload": "omRkYXRhlKJldmFsdWVEAAAAgGZidWNrZXRQAAAAAAAAAAAAAAAAAAAD26JldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAKJldmFsdWVEAAAAAGZidWNrZXRQAAAAAAAAAAAAAAAAAAAAAGlvcGVyYXRpb25paGlzdG9ncmFt",
      "key_id": "23597aae-6215-4fe9-8447-cb8e2cf80de8",
      "payload": "NPng8Biaa0V9HvzuhPmdZCT7qHZ7pzX1I8R1rGWJpVWLUM5g6b4j6DM7uep28pc+5SxMGLGL2ms0JjSthi5C5u9Uc+5ibdPUWvI9lasC7D8GRXaZhkAVBydOITFvQ28P/DFuQejpLyw+/GrY2dKd57SDj++aL2LE6cnQJxsP9INRvngu32CReaUVJ1f36hw0lztiJhTK6yYAdjyMawJjjiLLM1vf5qog1YUuz1buweJFukDhJIGAAPo6+Z5fiPt5VpmNoz5WCJMpajPyKp/vXBKy57EaC7OTCGHlGdvvbVzJGtWgMwrCPL61EahTdGtIniNBR+7/mT63yLMDnR2e9lssBITe01y3GiMHbloV2Uqfi4Vg7W44YglJ2aGU8oi8lyyxPuvBO8EkZGx5OglOQF7t+ZbfNqcw+4E1EaISWMvPlhGNNDjXcAK1IqWGbblEN7v3Q+BU/nBiwCaAHIpHRi9J3ZKXYLrSxb6yHDRP+za7CLKweKFUDMYW5n8/RDHLlwhzenbkUJx5pHjH9/DsVadAt6wvuHgQmiwsFH6AvlyuNXSD0yGZ5qy0+YyFsB5rIBDGSUuGa6hU4dq0jXJtfmzo1JOu4VMU1dYcZq1bJpuN/lwfQlIr9Q/BiwLVWRi6gm1yRA3ixvjwAqr/FQh5NH5zA9mwTf9d6Kkeh8NdIaY1URMuGSuaXXbOQ3hEFmQSr26Nlb2XDIqdVyOBTZyDVf2bXIZaBmaZxvnIyahfr55tgIlPudpuZNcDzxIK6tMvbjsAbnVq5eJuAhQUbVykH2PQIanHIK/hVGc8pQ1Qn34JqinBOt6KQf3FCvvCJBicepjT+cvHu+VN7FVOiOQhLNaBcLNDJiMz0DOEXcs1CWaekUry0NTjGAbZoHPI8kxPxSz9vl9eO5eSLCKj0ztAUS6BMRBen51vIqLvwTIROHEjIxGA1cc7DC6lMcL7PS0pM3rw9GQhLxEid5qz79rYsnGtIfuxkVFPF6ZCEihFWxa/swoAMmOySTu2n5SbyfR87l+rmbfr7xKstDnZAELQtv4Ap5N07Ha0XbgK"
    }
  ],
  "debug_key": "1234",
  "shared_info": "{\"api\":\"shared-storage\",\"debug_mode\":\"enabled\",\"report_id\":\"b15d20f7-11c7-431f-9310-8d6a69018a9e\",\"reporting_origin\":\"https://privacy-sandbox-demos-dsp.dev\",\"scheduled_report_time\":\"1719355379\",\"version\":\"0.1\"}"
}
```

**Comment by dbrito** [comment]
@maybellineboon Sorry for the deviation from the agenda, but after uploading some changes (more logs, debug path support) I noticed in Chrome internals that my report does not have debug enabled even though it worked perfectly locally 

*I created the debug keys (_**debug_key**_ and **_debug_reporting_** on source and trigger) as well as the cookie (**_ar_debug=1_**)

![image](https://github.com/user-attachments/assets/9c2c2eeb-3501-468f-8a5e-2e28a5379b68)

*debug_key has the same value on both steps (source and trigger)

Do you know if the debug has any operating limitations when it is being served via production?

Link with the implementation example:
https://partner.googleadservices.com/gampad/ads?gct=mQ8rkyFwrIsKwQGKGL0BKrABCAkQH0oAUhVmaWxlOi8vQ29tcG9zaXRlLmh0bWxYgICA4OvIyfOzAbgBk9fS8IME0gIJdGV4dC9odG1s8AKsAvgC-gGQAwHIA6wC0AP6AfADArgEst_yBcoFFmh0dHBzOi8vYWRzLnVvbC5jb20uYnKCBiwIst_yBRCAgIDg68jJ87MBGhAIABAAGAAggICA4P3pguIQIICAgOD96YLiDfoGAigBmggCEgDwCwGYDwKyAQIYAcoBAkABGL24xrQGKAAwvdT7uwY4AFgBagZfYmxhbmtwu-j1swY&iu=8804&gdfp_req=1&height=250&width=300&impl=ifr&sfv=1-0-40

**Comment by maybellineboon** [comment]
Hi @dbrito ,

I was checking your [link](https://partner.googleadservices.com/gampad/ads?gct=mQ8rkyFwrIsKwQGKGL0BKrABCAkQH0oAUhVmaWxlOi8vQ29tcG9zaXRlLmh0bWxYgICA4OvIyfOzAbgBk9fS8IME0gIJdGV4dC9odG1s8AKsAvgC-gGQAwHIA6wC0AP6AfADArgEst_yBcoFFmh0dHBzOi8vYWRzLnVvbC5jb20uYnKCBiwIst_yBRCAgIDg68jJ87MBGhAIABAAGAAggICA4P3pguIQIICAgOD96YLiDfoGAigBmggCEgDwCwGYDwKyAQIYAcoBAkABGL24xrQGKAAwvdT7uwY4AFgBagZfYmxhbmtwu-j1swY&iu=8804&gdfp_req=1&height=250&width=300&impl=ifr&sfv=1-0-40) and was able to see that on trigger, you also set the cookie. However, you're only setting `ar_debug=1; Path=/; HttpOnly; Secure`. You're missing the "SameSite=None;". So when you check `chrome://attribution-internals`, you'll observe that the debug_key is getting cleared on trigger but not on source. Please update the cookie to `ar_debug=1; Path=/; SameSite=None; HttpOnly; Secure`. This should fix the issue and help you get debug reports.

**Comment by dbrito** [comment]
Hi @maybellineboon Thank you very much, you are saving lifes here, I added the sameSite prop and now it is correct

Thank you one more time

Tomorrow I will generate the sample with the creative placement and with that I will follow up with the support

![image](https://github.com/user-attachments/assets/c1bb0afc-bcf7-426b-992d-f514f767fdc0)

**Comment by dbrito** [comment]
Hello @maybellineboon , how are you?

@maybellineboon I implemented debug and I was capturing some metrics for the test only that I noticed that not all captured reports had their debug version (debug_cleartext_payload and debug_mode property in shared_Info), would you know what scenario that would be possible ? Since debugging is enabled for everyone

*Because of this reporting scenario without debugging, the aggregation-service Job is always returning the error REPORTS_WITH_ERRORS_EXCEEDED_THRESHOLD 
```js
{
    "job_status": "FINISHED",
    "request_received_at": "2024-07-17T14:31:06.057168Z",
    "request_updated_at": "2024-07-17T14:31:03.113553793Z",
    "job_request_id": "report_2024_07_15_2",
    "input_data_blob_prefix": "2024_07_15/report_2024_07_15",
    "input_data_bucket_name": "uolcsm-uolads-aggregate-reports",
    "output_data_blob_prefix": "output/summary_report_2024_07_15.avro",
    "output_data_bucket_name": "uolcsm-uolads-aggregate-reports",
    "postback_url": "",
    "result_info": {
        "return_code": "REPORTS_WITH_ERRORS_EXCEEDED_THRESHOLD",
        "return_message": "Aggregation job failed early because the number of reports excluded from aggregation exceeded threshold.",
        "error_summary": {
            "error_counts": [
                {
                    "category": "DEBUG_NOT_ENABLED",
                    "count": 1,
                    "description": "Reports without shared_info.debug_mode enabled cannot be processed in a debug run."
                },
                {
                    "category": "NUM_REPORTS_WITH_ERRORS",
                    "count": 1,
                    "description": "Total number of reports that had an error. These reports were not considered in aggregation. See additional error messages for details on specific reasons."
                }
            ],
            "error_messages": []
        },
        "finished_at": "2024-07-17T14:31:03.110081155Z"
    },
    "job_parameters": {
        "debug_run": "true",
        "output_domain_bucket_name": "uolcsm-uolads-aggregate-reports",
        "output_domain_blob_prefix": "output_domain.avro",
        "attribution_report_to": "https://attribution.ads.uol.com.br"
    },
    "request_processing_started_at": "2024-07-17T14:31:02.933687572Z"
}
```

*Print of our bucket with both versions of the same report (with and without debug)
![image](https://github.com/user-attachments/assets/fb14e4d0-d718-4219-b3a1-52a39302f120)

Thank you in advance for your help

**Comment by maybellineboon** [comment]
Hi @dbrito ,

From the getJob error, it looks like one of the reports do not have debug_mode enabled. If some of your reports does not have the `\"debug_mode\":\"enabled\"` in the shared_info field, it means the report was generated in non-debug mode. You will not be able to batch these reports in `"debug_run": "true"` in Aggregation Service.

Please remove reports that do not have `\"debug_mode\":\"enabled\"` and try again.

**Comment by maybellineboon** [comment]
Hi @dbrito ,

You can batch the non-debug and debug reports together without the `"debug_run": "true"` in the createJob request. This will produce you a summary report for both debug and non-debug reports.

However, since we're trying to debug your reports and why you're observing a significantly lower aggregate, you'll have to run the rest of the debug reports on its own after. You should be able to re-run your debug reports and get the debug summary reports.

**Comment by dbrito** [comment]
Hi @maybellineboon , how are you?

Just updating the thread here, with debug enabled and the conditional to create report files only if they have the debug flag, the aggregation-service is working perfectly, the number of metrics is completely in accordance with the quantity of files created in the bucket


I still don't know why my api receives improper aggregate reports, but I'm going to test again without my conditional that only allows the creation of reports with debug, and with that see if the aggregation-service keeps returning the metric compatible with the number of creatives

**Comment by maybellineboon** [comment]
Hi @dbrito ,

Can you help elaborate more or share what you mean by improper aggregate reports?

Attribution Reporting API's aggregate reporting will randomly send null reports aside from real aggregate reports. This is for privacy reasons. The null reports does not impact the summary reports and does not contribute to any aggregate.

So, if you're testing on live traffic, you might randomly receive null reports.

**Comment by dbrito** [comment]
Hi @maybellineboon, 

So, the inappropriate reports would be exactly those that, with debug enabled, did not have a file with the clear_text_payload version. From what you explained, I now think I understand their origin, so these are null reports sent to protect users' privacy 

@maybellineboon, thank you very much for your help, without it I would still be banging my head

All the best there
