### ISSUE TITLE
Download link for LocalTestingTool does not work

### ISSUE THREAD

**Issue by alois-bissuel** [privacysandbox/aggregation-service#7]
The various links to get the local testing tool do not work (see for instance here https://github.com/privacysandbox/aggregation-service/blob/main/COLLECTING.md#produce-a-summary-report-locally).
Even replacing the {VERSION} by 0.4.0 in the [link](https://storage.googleapis.com/control-plane-shared-libraries-public-artifacts/%7BVERSION%7D/LocalTestingTool_%7BVERSION%7D.jar) does not solve the issue.

Thanks a lot!

P.S. I could get the previous release (ie 0.3.0) using the link available before the 0.4.0 release. See the [associated diff of the release](https://github.com/privacysandbox/aggregation-service/commit/8e065c1c1fcbf3340c508cc8c3771574ce4868e9).

**Comment by palenica** [comment]
Hi Alois, thank you for reporting. I believe the link is fixed now.

**Comment by alois-bissuel** [comment]
Indeed it is. Thanks a lot!
